# -*- coding: utf-8 -*-
"""weather_station

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VRZWupVhqsBLOpxfHw2s0tn4_rUshOq
"""

#CS 175
#Maggie Volker

weatherStation = input("Weather Station Name: ")
weatherStationName = weatherStation + " Weather Station"
temperature = float(input("What is the current temperature(Fahrenheit)? "))
windSpeed = int(input("What is the wind speed? "))
windDirection = input("What is the wind direction? ")
tempCelsius = ((temperature - 32) * 5/9)

print(f'{weatherStationName: >40}')
print()
print(f'{"Temperature(Fahrenheit):": >24}', f'{temperature: <5.1f}')
print(f'{"Temperature(Celsius): ": >25}', f'{tempCelsius: <5.1f}')
print(f'{"Wind Speed(mph): ": >25}', f'{windSpeed: <5}')
print(f'{"Wind Direction: ": >25}', f'{windDirection: <5}')